[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/mperaltad/ohmyzsh.git"
    clone.args = ["--depth=1 --branch manu --single-branch"]
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    clone.args = ["--depth=1"]
    pull.args = ["--depth=1"]
    refreshPeriod = "24h"
