font_family FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

confirm_os_window_close 0
macos_option_as_alt left
mouse_map alt+left press ungrabbed mouse_click_url

#background_opacity 0.95
# Catppuccin Mocha for Kitty
#background              #1e1e2e
background              #181825
cursor                  #f5e0dc

#shell bash -c 'if /opt/homebrew/bin/tmux attach-session -t main; then echo 1; else /opt/homebrew/bin/tmux; fi'
